### ISSUE TITLE
ts 枚举中 用中文做key 或者 变量名为中文 sync 的时候会报错

### ISSUE THREAD

**Issue by wcly** [didi/di18n#22]
例：
```typescript
export enum UpgradeModeEnum {
  '提示更新',
  '强制更新',
}
```

如果有上面这种写法，在运行 `npx di18n sync` 时会报错且中断执行。

报错信息如下：

```
/Users/weixiaolin/project/recipe_recording_app/node_modules/di18n-core/node_modules/@babel/types/lib/definitions/utils.js:112
    throw new TypeError(`Property ${key} of ${node.type} expected node to be of a type ${JSON.stringify(types)} but instead got ${JSON.stringify(val == null ? void 0 : val.type)}`);
          ^

TypeError: Property id of TSEnumMember expected node to be of a type ["Identifier","StringLiteral"] but instead got "CallExpression"
    at Object.validate (/Users/weixiaolin/project/recipe_recording_app/node_modules/di18n-core/node_modules/@babel/types/lib/definitions/utils.js:112:11)
    at validateField (/Users/weixiaolin/project/recipe_recording_app/node_modules/di18n-core/node_modules/@babel/types/lib/validators/validate.js:21:9)
    at validate (/Users/weixiaolin/project/recipe_recording_app/node_modules/di18n-core/node_modules/@babel/types/lib/validators/validate.js:15:3)
    at NodePath._replaceWith (/Users/weixiaolin/project/recipe_recording_app/node_modules/di18n-core/node_modules/@babel/traverse/lib/path/replacement.js:132:5)
    at NodePath.replaceWith (/Users/weixiaolin/project/recipe_recording_app/node_modules/di18n-core/node_modules/@babel/traverse/lib/path/replacement.js:118:8)
    at StringLiteral (/Users/weixiaolin/project/recipe_recording_app/node_modules/di18n-core/src/transform/transformJs.js:261:18)
    at NodePath._call (/Users/weixiaolin/project/recipe_recording_app/node_modules/di18n-core/node_modules/@babel/traverse/lib/path/context.js:45:20)
    at NodePath.call (/Users/weixiaolin/project/recipe_recording_app/node_modules/di18n-core/node_modules/@babel/traverse/lib/path/context.js:35:17)
    at NodePath.visit (/Users/weixiaolin/project/recipe_recording_app/node_modules/di18n-core/node_modules/@babel/traverse/lib/path/context.js:80:31)
    at TraversalContext.visitQueue (/Users/weixiaolin/project/recipe_recording_app/node_modules/di18n-core/node_modules/@babel/traverse/lib/context.js:86:16)
    at TraversalContext.visitSingle (/Users/weixiaolin/project/recipe_recording_app/node_modules/di18n-core/node_modules/@babel/traverse/lib/context.js:65:19)
    at TraversalContext.visit (/Users/weixiaolin/project/recipe_recording_app/node_modules/di18n-core/node_modules/@babel/traverse/lib/context.js:109:19)
    at traverseNode (/Users/weixiaolin/project/recipe_recording_app/node_modules/di18n-core/node_modules/@babel/traverse/lib/traverse-node.js:18:17)
    at NodePath.visit (/Users/weixiaolin/project/recipe_recording_app/node_modules/di18n-core/node_modules/@babel/traverse/lib/path/context.js:86:52)
    at TraversalContext.visitQueue (/Users/weixiaolin/project/recipe_recording_app/node_modules/di18n-core/node_modules/@babel/traverse/lib/context.js:86:16)
    at TraversalContext.visitMultiple (/Users/weixiaolin/project/recipe_recording_app/node_modules/di18n-core/node_modules/@babel/traverse/lib/context.js:61:17)
    at TraversalContext.visit (/Users/weixiaolin/project/recipe_recording_app/node_modules/di18n-core/node_modules/@babel/traverse/lib/context.js:107:19)
    at traverseNode (/Users/weixiaolin/project/recipe_recording_app/node_modules/di18n-core/node_modules/@babel/traverse/lib/traverse-node.js:18:17)
    at NodePath.visit (/Users/weixiaolin/project/recipe_recording_app/node_modules/di18n-core/node_modules/@babel/traverse/lib/path/context.js:86:52)
    at TraversalContext.visitQueue (/Users/weixiaolin/project/recipe_recording_app/node_modules/di18n-core/node_modules/@babel/traverse/lib/context.js:86:16)
    at TraversalContext.visitSingle (/Users/weixiaolin/project/recipe_recording_app/node_modules/di18n-core/node_modules/@babel/traverse/lib/context.js:65:19)
    at TraversalContext.visit (/Users/weixiaolin/project/recipe_recording_app/node_modules/di18n-core/node_modules/@babel/traverse/lib/context.js:109:19)
    at traverseNode (/Users/weixiaolin/project/recipe_recording_app/node_modules/di18n-core/node_modules/@babel/traverse/lib/traverse-node.js:18:17)
    at NodePath.visit (/Users/weixiaolin/project/recipe_recording_app/node_modules/di18n-core/node_modules/@babel/traverse/lib/path/context.js:86:52)
    at TraversalContext.visitQueue (/Users/weixiaolin/project/recipe_recording_app/node_modules/di18n-core/node_modules/@babel/traverse/lib/context.js:86:16)
    at TraversalContext.visitMultiple (/Users/weixiaolin/project/recipe_recording_app/node_modules/di18n-core/node_modules/@babel/traverse/lib/context.js:61:17)
    at TraversalContext.visit (/Users/weixiaolin/project/recipe_recording_app/node_modules/di18n-core/node_modules/@babel/traverse/lib/context.js:107:19)
    at traverseNode (/Users/weixiaolin/project/recipe_recording_app/node_modules/di18n-core/node_modules/@babel/traverse/lib/traverse-node.js:18:17)
    at NodePath.visit (/Users/weixiaolin/project/recipe_recording_app/node_modules/di18n-core/node_modules/@babel/traverse/lib/path/context.js:86:52)
    at TraversalContext.visitQueue (/Users/weixiaolin/project/recipe_recording_app/node_modules/di18n-core/node_modules/@babel/traverse/lib/context.js:86:16)
    at TraversalContext.visitSingle (/Users/weixiaolin/project/recipe_recording_app/node_modules/di18n-core/node_modules/@babel/traverse/lib/context.js:65:19)
    at TraversalContext.visit (/Users/weixiaolin/project/recipe_recording_app/node_modules/di18n-core/node_modules/@babel/traverse/lib/context.js:109:19)
    at traverseNode (/Users/weixiaolin/project/recipe_recording_app/node_modules/di18n-core/node_modules/@babel/traverse/lib/traverse-node.js:18:17)
    at traverse (/Users/weixiaolin/project/recipe_recording_app/node_modules/di18n-core/node_modules/@babel/traverse/lib/index.js:49:34)
    at transformJs (/Users/weixiaolin/project/recipe_recording_app/node_modules/di18n-core/src/transform/transformJs.js:489:3)
    at transformTs (/Users/weixiaolin/project/recipe_recording_app/node_modules/di18n-core/src/transform/transformTs.js:23:10)
    at transformReact (/Users/weixiaolin/project/recipe_recording_app/node_modules/di18n-core/src/transform/transformZeroToDi18n.js:22:32)
    at transformZeroToDi18n (/Users/weixiaolin/project/recipe_recording_app/node_modules/di18n-core/src/transform/transformZeroToDi18n.js:98:3)
    at /Users/weixiaolin/project/recipe_recording_app/node_modules/di18n-cli/src/command/collect.js:215:5
    at Array.forEach (<anonymous>)
    at collectChineseWords (/Users/weixiaolin/project/recipe_recording_app/node_modules/di18n-cli/src/command/collect.js:214:15)
```

**Comment by jsm1003** [comment]
@wcly 这个 bug 有同学前段时间提过了，再修改，你可以先参照这个 issue 里面修改下试试 https://github.com/didi/di18n/issues/10

**Comment by jsm1003** [comment]
@wcly 或者你也可以在不需要转换的代码行前面加上 // di18n-disable 试试

**Comment by wcly** [comment]
好的，感谢。

**Comment by wcly** [comment]
> @wcly 或者你也可以在不需要转换的代码行前面加上 // di18n-disable 试试

试了，不行。
另外，测试了一下，中文对象key会报错，只有加引号才会
```js
// 报错
export default {
  '中文': 0,
};

// 报错
export default {
  "中文": 0,
};

// 不报错
export default {
  中文: 0,
};
```

**Comment by jsm1003** [comment]
1. 注释一个段落
/* di18n-disable */
class Demo extends React.Component {
  render() {
    return <div>注释忽略翻译</div>;
  }
}
/* di18n-enable */

2. 注释单独一行
class Demo extends React.Component {
  render() {
    return <div>注释忽略翻译</div>; // di18n-disable-line
  }
}
@wcly 这里有两个实例，你再试下

**Comment by wcly** [comment]
> ```js
> /* di18n-enable */
> ```

这个可以

**Comment by wcly** [comment]
> 1. 注释一个段落
> 
> ```js
> /* di18n-disable */
> class Demo extends React.Component {
>   render() {
>     return <div>注释忽略翻译</div>;
>   }
> }
> /* di18n-enable */
> ```
> 
> 2. 注释单独一行
> 
> ```js
> class Demo extends React.Component {
>   render() {
>     return <div>注释忽略翻译</div>; // di18n-disable-line
>   }
> }
> ```
> 
> @wcly 这里有两个示例，你再试下

试了，这个两个可以

**Comment by jsm1003** [comment]
0.1.29 版本修复了@wcly
